# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Profile',
        ),
    ]
